export default {
  demo: 'https://demo.parca.dev/',
  documentation: 'https://www.parca.dev/docs/overview',
  download: 'https://www.parca.dev/docs/quickstart',
  tutorials: 'https://www.parca.dev/docs/binary',
  binary: 'https://www.parca.dev/docs/binary',
  kubernetes: 'https://www.parca.dev/docs/kubernetes',
  overview: 'https://www.parca.dev/docs/overview',
  faq: 'https://www.parca.dev/docs/faq',
  github: 'https://github.com/parca-dev/parca',
  twitter: 'https://twitter.com/ParcaDev',
  discord: 'https://discord.com/invite/ZgUpYgpzXy',
  youtube: 'https://www.youtube.com/channel/UCRrqAGuajRqIX_E_arNnYCw',
  mastodon: 'https://fosstodon.org/@parca',
  slack: 'https://cloud-native.slack.com/archives/C01BB0M6K1U',
  license: 'https://www.apache.org/licenses/LICENSE-2.0',
};
